circuit_to_BDD_manager Class Reference
Class to convert circuits nodes into BDD nodes.
#include <circuit_to_BDD_manager.hpp>
Public Member Functions
circuit_to_BDD_manager (ClassProject::ManagerInterface *BDD_manager_iface)
Constructor.
~circuit_to_BDD_manager ()
Destructor.
void GenerateBDD (list_of_circuit_t circuit, std::string benchmark_file)
generates BDD from the circuit nodes provided.
void PrintBDD (std::set< label_t > set_of_output_labels)
Private Member Functions
ClassProject::BDD_ID circuitId2BDDid (unique_ID_t node)
returns the BDD_ID of the given circuit ID.
ClassProject::BDD_ID InputGate (label_t label)
generates the BDD node equivalent to a variable with label `label`.
ClassProject::BDD_ID NotGate (set_of_circuit_t node)
generates the BDD node equivalent to the NOT gate.
ClassProject::BDD_ID AndGate (set_of_circuit_t inputNodes)
generates the BDD node equivalent to the AND gate.
ClassProject::BDD_ID OrGate (set_of_circuit_t inputNodes)
generates the BDD node equivalent to the OR gate.
ClassProject::BDD_ID NandGate (set_of_circuit_t inputNodes)
generates the BDD node equivalent to the NAND gate.
ClassProject::BDD_ID NorGate (set_of_circuit_t inputNodes)
generates the BDD node equivalent to the NOR gate.
ClassProject::BDD_ID XorGate (set_of_circuit_t inputNodes)
generates the BDD node equivalent to the XOR gate.
Private Attributes
boost::unordered_map< unique_ID_t, ClassProject::BDD_ID > node2BDDTable
Mapping from circuit node unique IDs to BDD IDs.
std::unordered_map< label_t, ClassProject::BDD_ID > label2BDD_ID_table
Mapping from node's label to BDD IDs.
ClassProject::ManagerInterface * BDD_manager
std::string result_dir
Directory where the results are stored.
Detailed Description
Class to convert circuits nodes into BDD nodes.
Circuit nodes are generated by the class bench_circuit_manager.
Authors
{Carolina Nogueira}
Constructor & Destructor Documentation
circuit_to_BDD_manager::circuit_to_BDD_manager (ClassProject::ManagerInterface * BDD_manager_iface)
Constructor.
Parameters
BDD_manager_iface is ClassProject::ManagerInterface Constructor method for the circuit_to_BDD_manager class.
circuit_to_BDD_manager::~circuit_to_BDD_manager ()
Destructor.
Parameters
none Destructor method for the circuit_to_BDD_manager class.
Member Function Documentation
ClassProject::BDD_ID circuit_to_BDD_manager::AndGate (set_of_circuit_t inputNodes) [private]
generates the BDD node equivalent to the AND gate.
Parameters
node is set_of_circuit_t containing the circuit IDs of the gates to be used as input.
Returns
ClassProject::BDD_ID
References circuitId2BDDid().
Referenced by GenerateBDD(), and NandGate().
ClassProject::BDD_ID circuit_to_BDD_manager::circuitId2BDDid (unique_ID_t node) [private]
returns the BDD_ID of the given circuit ID.
Parameters
node is unique_ID_t
Returns
ClassProject::BDD_ID
References node2BDDTable.
Referenced by AndGate(), GenerateBDD(), NandGate(), NorGate(), NotGate(), OrGate(), and XorGate().
void circuit_to_BDD_manager::GenerateBDD (list_of_circuit_t circuit, std::string benchmark_file)
generates BDD from the circuit nodes provided.
Parameters
circuit is list_of_circuit_t - topologic sorted list containing the circuit nodes
Returns
none
Generates the calls to the BDD package in order to generate the BDD equivalent to the provided circuit.
References AndGate(), circuitId2BDDid(), InputGate(), label2BDD_ID_table, NandGate(), node2BDDTable, NorGate(), NotGate(), OrGate(), result_dir, and XorGate().
ClassProject::BDD_ID circuit_to_BDD_manager::InputGate (label_t label) [private]
generates the BDD node equivalent to a variable with label `label`.
Parameters
label is label_t
Returns
ClassProject::BDD_ID
Referenced by GenerateBDD().
ClassProject::BDD_ID circuit_to_BDD_manager::NandGate (set_of_circuit_t inputNodes) [private]
generates the BDD node equivalent to the NAND gate.
Parameters
node is set_of_circuit_t containing the circuit IDs of the gates to be used as input.
Returns
ClassProject::BDD_ID
References AndGate(), and circuitId2BDDid().
Referenced by GenerateBDD().
ClassProject::BDD_ID circuit_to_BDD_manager::NorGate (set_of_circuit_t inputNodes) [private]
generates the BDD node equivalent to the NOR gate.
Parameters
node is set_of_circuit_t containing the circuit IDs of the gates to be used as input.
Returns
ClassProject::BDD_ID
References circuitId2BDDid(), and OrGate().
Referenced by GenerateBDD().
ClassProject::BDD_ID circuit_to_BDD_manager::NotGate (set_of_circuit_t node) [private]
generates the BDD node equivalent to the NOT gate.
Parameters
node is set_of_circuit_t containing the circuit ID of the gate to be inverted.
Returns
ClassProject::BDD_ID
References circuitId2BDDid().
Referenced by GenerateBDD().
ClassProject::BDD_ID circuit_to_BDD_manager::OrGate (set_of_circuit_t inputNodes) [private]
generates the BDD node equivalent to the OR gate.
Parameters
node is set_of_circuit_t containing the circuit IDs of the gates to be used as input.
Returns
ClassProject::BDD_ID
References circuitId2BDDid().
Referenced by GenerateBDD(), and NorGate().
ClassProject::BDD_ID circuit_to_BDD_manager::XorGate (set_of_circuit_t inputNodes) [private]
generates the BDD node equivalent to the XOR gate.
Parameters
node is set_of_circuit_t containing the circuit IDs of the gates to be used as input.
Returns
ClassProject::BDD_ID
References circuitId2BDDid(), label2BDD_ID_table, and result_dir.
Referenced by GenerateBDD().
The documentation for this class was generated from the following files:
/home/felipe/Desktop/vdsproject/vdscp_04/src/bench/circuit_to_BDD_manager.hpp
/home/felipe/Desktop/vdsproject/vdscp_04/src/bench/circuit_to_BDD_manager.cpp