ClassProject::Manager Class Reference
Manager Class.
#include <Manager.h>
Public Member Functions
Manager ()
Manager Class.
BDD_ID createVar (const std::string &label) override
Function to create a new Variable.
const BDD_ID & True () override
Function to return the id of the TRUE leaf node in the Binary Tree.
const BDD_ID & False () override
Function to return the id of the FALSE leaf node in the Binary Tree.
bool isConstant (const BDD_ID f) override
Function to test if a given BDD_ID is a Constant.
bool isVariable (const BDD_ID x) override
Function to test if a given BDD_ID is a Variable.
BDD_ID topVar (const BDD_ID f) override
Function to return the top variable of a given BDD_ID.
BDD_ID ite (const BDD_ID i, const BDD_ID t, const BDD_ID e) override
Function to compute the IF(BDD_ID i) then(BDD_ID t) ELSE(BDD_ID e) Operator.
BDD_ID coFactorTrue (const BDD_ID f, BDD_ID x) override
Function to compute the TRUE coFactor of a given BDD_ID f with respect to BDD_ID x.
BDD_ID coFactorFalse (const BDD_ID f, BDD_ID x) override
Function to compute the FALSE coFactor of a given BDD_ID f with respect to BDD_ID x.
BDD_ID coFactorTrue (const BDD_ID f) override
Function to compute the TRUE coFactor of a given BDD_ID f.
BDD_ID coFactorFalse (const BDD_ID f) override
Function to compute the FALSE coFactor of a given BDD_ID f.
BDD_ID and2 (const BDD_ID a, const BDD_ID b) override
Function to compute an AND Boolean Function of two given BDD_IDs a and b.
BDD_ID or2 (const BDD_ID a, const BDD_ID b) override
Function to compute an OR Boolean Function of two given BDD_IDs a and b.
BDD_ID xor2 (const BDD_ID a, const BDD_ID b) override
Function to compute an XOR Boolean Function of two given BDD_IDs a and b.
BDD_ID neg (const BDD_ID a) override
Function to compute the Negation of a given BDD_ID.
BDD_ID nand2 (const BDD_ID a, const BDD_ID b) override
Function to compute a NAND Boolean Function of two given BDD_IDs a and b.
BDD_ID nor2 (const BDD_ID a, const BDD_ID b) override
Function to compute a NOR Boolean Function of two given BDD_IDs a and b.
std::string getTopVarName (const BDD_ID &root) override
Function to get the name of the Top Variable of a given BDD_ID.
void findNodes (const BDD_ID &root, std::set< BDD_ID > &nodes_of_root) override
Function to find out all the reachable nodes in the Binary Tree starting from a given BDD_ID.
void findVars (const BDD_ID &root, std::set< BDD_ID > &vars_of_root) override
Function to find out all the reachable Variables in the Binary Tree starting from a given BDD_ID.
size_t uniqueTableSize () override
Function to return the size of the uniqueTable.
size_t newNodesSize ()
Function to return the size of the new_nodes.
size_t computedTableSize ()
Function to return the size of the Computed Table.
const BDD_Node & getBDDNode (BDD_ID id)
Function to return a BDD_Node from the uniqueTable according to its BDD_ID.
void printUniqueTable ()
Function to print all the BDD_Nodes present in the uniqueTable, new_nodes table and in the computed table.
Private Member Functions
bool isComplement (BDD_ID f)
Function check if a given BDD_ID is a complement of a previous BDD_ID.
BDD_ID getComplement (BDD_ID f)
Function to return the coplement of a given BDD_ID.
BDD_ID getNextId (BDD_ID f)
Function to get the next ID of a given BDD_ID.
BDD_ID iteST (const BDD_ID i, const BDD_ID t, const BDD_ID e)
Function to compute the ite according to the standard triples.
BDD_ID ite (const BDD_ID i, const BDD_ID t, const BDD_ID e, const BDD_ID top_var)
Function to compute the IF(BDD_ID i) then(BDD_ID t) ELSE(BDD_ID e) Operator of a given BDD_ID with respect to its top variable.
BDD_ID iteC (const BDD_ID i, const BDD_ID t, const BDD_ID e, const BDD_ID top_var)
Function to compute the COMPLEMENT IF(BDD_ID i) then(BDD_ID t) ELSE(BDD_ID e) Operator of a given BDD_ID with respect to its top variable.
Private Attributes
BDD_ID falseNode = BDD_ID_FALSE
BDD_ID trueNode = BDD_ID_TRUE
vector< BDD_Node > unique_table
unordered_map< BDD_Node, BDD_ID, BDDHasher, BDDComparer > new_nodes
unordered_map< BDD_Node, BDD_ID, BDDHasher, BDDComparer > computed_table
Detailed Description
Manager Class.
Declaration of the functions from the ManagerInterface.
Constructor & Destructor Documentation
Manager::Manager ()
Manager Class.
Implements the virtual functions from the ManagerInterface.Manager Constructor. BDD_Node trueNode.
Initiates the TRUE leaf of node the Binary Tree.
Member Function Documentation
BDD_ID Manager::and2 (const BDD_ID a, const BDD_ID b) [override], [virtual]
Function to compute an AND Boolean Function of two given BDD_IDs a and b.
Parameters
a a BDD_ID argument.
b a BDD_ID argument.id
Returns
Return the computed ITE operator of BDD_IDs a and b according to the AND Function.
Implements ClassProject::ManagerInterface .
References ite().
BDD_ID Manager::coFactorFalse (const BDD_ID f, BDD_ID x) [override], [virtual]
Function to compute the FALSE coFactor of a given BDD_ID f with respect to BDD_ID x.
Parameters
f a BDD_ID argument.
x a BDD_ID argument.
Returns
Return the computed ITE operator of the TRUE, and FALSE branches of BDD_ID f with respect to BDD_ID x.
Implements ClassProject::ManagerInterface .
References coFactorTrue(), getComplement(), isComplement(), isConstant(), ite(), and topVar().
Referenced by coFactorTrue(), findNodes(), findVars(), ite(), and iteC().
BDD_ID Manager::coFactorFalse (const BDD_ID f) [override], [virtual]
Function to compute the FALSE coFactor of a given BDD_ID f.
Parameters
f a BDD_ID argument.
Returns
Return the FALSE coFactor of the given BDD_ID f.
Implements ClassProject::ManagerInterface .
References getBDDNode(), and ClassProject::BDD_Node::low.
BDD_ID Manager::coFactorTrue (const BDD_ID f, BDD_ID x) [override], [virtual]
Function to compute the TRUE coFactor of a given BDD_ID f with respect to BDD_ID x.
Parameters
f a BDD_ID argument.
x a BDD_ID argument.
Returns
Return the computed ITE operator of the TRUE, and FALSE branches of BDD_ID f with respect to BDD_ID x.
Implements ClassProject::ManagerInterface .
References coFactorFalse(), getComplement(), isComplement(), isConstant(), ite(), and topVar().
Referenced by coFactorFalse(), findNodes(), findVars(), ite(), and iteC().
BDD_ID Manager::coFactorTrue (const BDD_ID f) [override], [virtual]
Function to compute the TRUE coFactor of a given BDD_ID f.
Parameters
f a BDD_ID argument.
Returns
Return the TRUE coFactor of the given BDD_ID f.
Implements ClassProject::ManagerInterface .
References getBDDNode(), and ClassProject::BDD_Node::high.
size_t Manager::computedTableSize ()
Function to return the size of the Computed Table.
Returns
the size of computed_table.
References computed_table.
BDD_ID Manager::createVar (const std::string & label) [override], [virtual]
Function to create a new Variable.
Parameters
label a string argument.
Returns
The id of the new variable which correspond to the size of the uniqueTable.
BDD_ID value id.
BDD_Node value var.
Implements ClassProject::ManagerInterface .
const BDD_ID & Manager::False () [override], [virtual]
Function to return the id of the FALSE leaf node in the Binary Tree.
Returns
The id of the False leaf node in the Binary Tree.
Implements ClassProject::ManagerInterface .
void Manager::findNodes (const BDD_ID & root, std::set< BDD_ID > & nodes_of_root) [override], [virtual]
Function to find out all the reachable nodes in the Binary Tree starting from a given BDD_ID.
Parameters
root a BDD_ID argument.
Returns
Return set containing all the reachable Nodes from a given Node.
Implements ClassProject::ManagerInterface .
References coFactorFalse(), coFactorTrue(), and isConstant().
void Manager::findVars (const BDD_ID & root, std::set< BDD_ID > & vars_of_root) [override], [virtual]
Function to find out all the reachable Variables in the Binary Tree starting from a given BDD_ID.
Parameters
root a BDD_ID argument.
Returns
Return set containing all the reachable Variables from a given Node.
Implements ClassProject::ManagerInterface .
References coFactorFalse(), coFactorTrue(), isConstant(), and topVar().
const BDD_Node & Manager::getBDDNode (BDD_ID id)
Function to return a BDD_Node from the uniqueTable according to its BDD_ID.
Parameters
id a BDD_ID argument.
Returns
Return a BDD_Node from the uniqueTable that has the corresponding BDD_ID.
References isConstant().
Referenced by coFactorFalse(), coFactorTrue(), getTopVarName(), isVariable(), and topVar().
BDD_ID Manager::getComplement (BDD_ID f) [private]
Function to return the coplement of a given BDD_ID.
Parameters
f a BDD_ID argument.
Returns
BDD_ID_TRUE or FALSE if f is a constant, otherwise return the BDD_ID of f +1 if BDD_ID is even, or BDD_ID -1 if it's odd.
References isConstant().
Referenced by coFactorFalse(), coFactorTrue(), ite(), iteC(), and iteST().
BDD_ID Manager::getNextId (BDD_ID f) [private]
Function to get the next ID of a given BDD_ID.
Parameters
f a BDD_ID argument.
Returns
the next BDD_ID of f.
References isComplement().
Referenced by iteST().
std::string Manager::getTopVarName (const BDD_ID & root) [override], [virtual]
Function to get the name of the Top Variable of a given BDD_ID.
Parameters
root a BDD_ID argument.
Returns
Return the label(Top Varaible Name) of the given BDD_ID root.
Implements ClassProject::ManagerInterface .
References getBDDNode().
bool Manager::isComplement (BDD_ID f) [private]
Function check if a given BDD_ID is a complement of a previous BDD_ID.
Table that contains the computed ite calculations in order to eliminate reptition on the computations.
Parameters
f a BDD_ID argument.
Returns
TRUE in the case of f be a complent BDD_ID, otherwise return FALSE.
References isConstant().
Referenced by coFactorFalse(), coFactorTrue(), getNextId(), and ite().
bool Manager::isConstant (const BDD_ID f) [override], [virtual]
Function to test if a given BDD_ID is a Constant.
Parameters
f a BDD_ID argument.
Returns
TRUE in case that the given BDD_ID f is a Constant, otherwise return FALSE.
Implements ClassProject::ManagerInterface .
Referenced by coFactorFalse(), coFactorTrue(), findNodes(), findVars(), getBDDNode(), getComplement(), isComplement(), isVariable(), ite(), and iteST().
bool Manager::isVariable (const BDD_ID x) [override], [virtual]
Function to test if a given BDD_ID is a Variable.
Parameters
x a BDD_ID argument.
Returns
TRUE in case that the given BDD_ID x is a Variable, otherwise return FALSE.
< BDD_Node pointer value node.
Implements ClassProject::ManagerInterface .
References getBDDNode(), isConstant(), and ClassProject::BDD_Node::top_var.
BDD_ID Manager::ite (const BDD_ID i, const BDD_ID t, const BDD_ID e, const BDD_ID top_var) [private]
Function to compute the IF(BDD_ID i) then(BDD_ID t) ELSE(BDD_ID e) Operator of a given BDD_ID with respect to its top variable.
Parameters
i a BDD_ID argument.
t a BDD_ID argument.
e a BDD_ID argument.
top_var a BDD_ID argument.
Returns
Return the id of the computed IF then ELSE Operator.
References coFactorFalse(), coFactorTrue(), computed_table, getComplement(), isComplement(), iteC(), new_nodes, and uniqueTableSize().
Referenced by and2(), coFactorFalse(), coFactorTrue(), ite(), iteC(), iteST(), nand2(), neg(), nor2(), or2(), and xor2().
BDD_ID Manager::ite (const BDD_ID i, const BDD_ID t, const BDD_ID e) [override], [virtual]
Function to compute the IF(BDD_ID i) then(BDD_ID t) ELSE(BDD_ID e) Operator.
Parameters
i a BDD_ID argument.
t a BDD_ID argument.
e a BDD_ID argument.
Returns
Return the id of the computed IF then ELSE Operator.
Implements ClassProject::ManagerInterface .
References getComplement(), isConstant(), ite(), iteST(), and topVar().
BDD_ID Manager::iteC (const BDD_ID i, const BDD_ID t, const BDD_ID e, const BDD_ID top_var) [private]
Function to compute the COMPLEMENT IF(BDD_ID i) then(BDD_ID t) ELSE(BDD_ID e) Operator of a given BDD_ID with respect to its top variable.
Parameters
i a BDD_ID argument.
t a BDD_ID argument.
e a BDD_ID argument.
top_var a BDD_ID argument.
Returns
Return the id of the computed IF then ELSE Operator.
References coFactorFalse(), coFactorTrue(), computed_table, getComplement(), ite(), new_nodes, and uniqueTableSize().
Referenced by ite().
BDD_ID Manager::iteST (const BDD_ID i, const BDD_ID t, const BDD_ID e) [private]
Function to compute the ite according to the standard triples.
Parameters
i a BDD_ID argument.
t a BDD_ID argument.
e a BDD_ID argument.
Returns
the ID of the computed IF THEN ELSE operator according to the standard triples.
References getComplement(), getNextId(), isConstant(), ite(), and topVar().
Referenced by ite().
BDD_ID Manager::nand2 (const BDD_ID a, const BDD_ID b) [override], [virtual]
Function to compute a NAND Boolean Function of two given BDD_IDs a and b.
Parameters
a a BDD_ID argument.
b a BDD_ID argument.
Returns
Return the computed ITE operator of BDD_IDs a and b according to the NAND Function.
Implements ClassProject::ManagerInterface .
References ite(), and neg().
BDD_ID Manager::neg (const BDD_ID a) [override], [virtual]
Function to compute the Negation of a given BDD_ID.
Parameters
a a BDD_ID argument.
Returns
Return the Negation of a given BDD_ID.
Implements ClassProject::ManagerInterface .
References ite().
Referenced by nand2(), nor2(), and xor2().
size_t Manager::newNodesSize ()
Function to return the size of the new_nodes.
Returns
the size of new_nodes.
References new_nodes.
BDD_ID Manager::nor2 (const BDD_ID a, const BDD_ID b) [override], [virtual]
Function to compute a NOR Boolean Function of two given BDD_IDs a and b.
Parameters
a a BDD_ID argument.
b a BDD_ID argument.
Returns
Return the computed ITE operator of BDD_IDs a and b according to the NOR Function.
Implements ClassProject::ManagerInterface .
References ite(), and neg().
BDD_ID Manager::or2 (const BDD_ID a, const BDD_ID b) [override], [virtual]
Function to compute an OR Boolean Function of two given BDD_IDs a and b.
Parameters
a a BDD_ID argument.
b a BDD_ID argument.
Returns
Return the computed ITE operator of BDD_IDs a and b according to the OR Function.
Implements ClassProject::ManagerInterface .
References ite().
BDD_ID Manager::topVar (const BDD_ID f) [override], [virtual]
Function to return the top variable of a given BDD_ID.
Parameters
f a BDD_ID argument.
Returns
Return the top variable of the given BDD_ID.
Implements ClassProject::ManagerInterface .
References getBDDNode(), and ClassProject::BDD_Node::top_var.
Referenced by coFactorFalse(), coFactorTrue(), findVars(), ite(), and iteST().
const BDD_ID & Manager::True () [override], [virtual]
Function to return the id of the TRUE leaf node in the Binary Tree.
Returns
The id of the TRUE leaf node in the Binary Tree.
Implements ClassProject::ManagerInterface .
size_t Manager::uniqueTableSize () [override], [virtual]
Function to return the size of the uniqueTable.
Returns
The size_t of the uniqueTable.
Implements ClassProject::ManagerInterface .
Referenced by ite(), and iteC().
BDD_ID Manager::xor2 (const BDD_ID a, const BDD_ID b) [override], [virtual]
Function to compute an XOR Boolean Function of two given BDD_IDs a and b.
Parameters
a a BDD_ID argument.
b a BDD_ID argument.
Returns
Return the computed ITE operator of BDD_IDs a and b according to the XOR Function.
Implements ClassProject::ManagerInterface .
References ite(), and neg().
Member Data Documentation
unordered_map<BDD_Node,BDD_ID,BDDHasher,BDDComparer> ClassProject::Manager::computed_table [private]
Holds the nodes from the unique table.
Referenced by computedTableSize(), ite(), iteC(), and printUniqueTable().
unordered_map<BDD_Node,BDD_ID,BDDHasher,BDDComparer> ClassProject::Manager::new_nodes [private]
Vector that represents the unique_table.
Referenced by ite(), iteC(), newNodesSize(), and printUniqueTable().
The documentation for this class was generated from the following files:
/home/felipe/Desktop/vdsproject/vdscp_04/src/Manager.h
/home/felipe/Desktop/vdsproject/vdscp_04/src/Manager.cpp