bench_circuit_manager Class Reference
Class to convert bench nodes into circuits nodes.
#include <bench_circuit_manager.hpp>
Public Member Functions
bench_circuit_manager (std::string bench_file)
Constructor.
~bench_circuit_manager ()
Destructor.
list_of_circuit_t GetSortedCircuit (void)
return the list of circuit nodes topologically sorted.
std::set< label_t > GetListOfOutputLabels (void)
return a list with the labels of the OUTPUT gates of the circuit.
Private Member Functions
void PrintLabelsTable (void)
Print the labels2node_table table.
void PrintUUIDCircuitTable (void)
Print the uuid2circuitNode_table table.
void PrintOutputList (void)
Print the set_of_output_labels list.
void PrintLabels2UUIDTable (void)
Print the labels2uuid_table table.
void PrintCircuit (unique_ID_t circuit_ID, int indent)
prints the circuit starting from the given unique identificator.
void PrintCircuitByLabel (label_t node_label)
prints the circuit starting from the given label's node.
void PrintCircuitsOfOutputSet (void)
prints all circuits from the set of circuit OUTPUTS.
void PrintSortedCircuitList (void)
prints the list of topological sorted circuit's node.
set_of_circuit_t GetListOfCircuitsInputs (void)
return a list with the UUID of the INPUT gates of the circuit.
set_of_circuit_t GetListOfCircuitsOutputs (void)
return a list with the UUID of the OUTPUT gates of the circuit.
circuit_node_type GetCircuitNode (unique_ID_t circuit_node_uuid)
return a circuit node, given a its unique ID.
boost::unordered_map< unique_ID_t, circuit_node_type > GetCircuit (void)
return the table representing the circuit.
bool ParseFile (std::string bench_file)
Reads the file containing the circuit in the bench format.
bool AddToLabelsTable (bench_node_t bench_node)
return the list of circuit nodes topologically sorted.
unique_ID_t FindOrAddToCircuit (bench_node_t bench_node)
search or add the node to the circuit.
unique_ID_t FindOrAddToCircuitbyLabel (label_t node_label)
find or add a node to the circuit given its label.
circuit_node_type BenchNode2CircuitNode (bench_node_t bench_node)
converts bench node to circuit node.
void CreateCircuitFromOutputList (void)
create a circuit from the labels in the set_of_output_labels.
void CreateCircuitbyLabel (label_t bnode_label)
create a circuit from the given node's label.
void TopologicalSortKahnsAlgorithm (void)
Implementation of Kahn's Algorithm for topological sort.
bool IsUniqueOutgoingEdge (unique_ID_t src_node, unique_ID_t dst_node)
auxiliar function for topological sort algorithms.
Private Attributes
unique_ID_t ID_counter
boost::uuids::random_generator generator
std::set< label_t > set_of_output_labels
Set containing bench node labels of all OUTPUT gates.
std::set< label_t > set_of_flipflop_labels
Set containing bench node labels of all FLIP FLOP gates.
std::set< label_t > outputs
set_of_circuit_t set_of_circuit_OUT
Set containing the unique ID of all OUTPUT gates.
set_of_circuit_t set_of_circuit_IN
Set containing the unique ID of all INPUT gates.
std::unordered_map< label_t, bench_node_t > labels2node_table
Mapping from bench node labels to bench node.
std::unordered_map< label_t, unique_ID_t > labels2uuid_table
Mapping from bench node labels to circuit unique IDs.
boost::unordered_map< unique_ID_t, circuit_node_type > uuid2circuitNode_table
Mapping from circuit unique IDs to circuit nodes.
list_of_circuit_t sorted_circuit
List contained the topological sorted circuit nodes.
Detailed Description
Class to convert bench nodes into circuits nodes.
Bench nodes are generated by parsing ISCAS85/89/99 bench format files.
Authors
{Carolina Nogueira}
Constructor & Destructor Documentation
bench_circuit_manager::bench_circuit_manager (std::string bench_file)
Constructor.
Parameters
bench_file is std::string. Constructor method for the bench_circuit_manager class. It generates the topological circuit described in the file bench_file that must be in the ISCAS85/ISCAS89/ISCAS99 format.
References CreateCircuitFromOutputList(), labels2node_table, labels2uuid_table, ParseFile(), set_of_circuit_IN, set_of_circuit_OUT, set_of_flipflop_labels, set_of_output_labels, TopologicalSortKahnsAlgorithm(), and uuid2circuitNode_table.
bench_circuit_manager::~bench_circuit_manager ()
Destructor.
Parameters
none Destructor method for the bench_circuit_manager class.
Member Function Documentation
bool bench_circuit_manager::AddToLabelsTable (bench_node_t bench_node) [private]
return the list of circuit nodes topologically sorted.
Parameters
bench_node is bench_node_t
Returns
bool: true -> Node successfully added false -> Node already exist and could not be added
Adds a node to the labels table (labels2node) and to the sets_of_outputs in case it is of gate type OUTPUT.
References labels2node_table, set_of_flipflop_labels, and set_of_output_labels.
Referenced by ParseFile().
circuit_node_type bench_circuit_manager::BenchNode2CircuitNode (bench_node_t bench_node) [private]
converts bench node to circuit node.
Parameters
bench_node is bench_node_t and represents the node to be converted.
Returns
circuit_node_type
Given a bench_node_t, it converts the node into an circuit_node_type.
References FindOrAddToCircuitbyLabel(), circuit_node_type::gate_type, circuit_node_type::ID, circuit_node_type::input_ID_list, circuit_node_type::label, set_of_circuit_IN, and uuid2circuitNode_table.
Referenced by FindOrAddToCircuit().
void bench_circuit_manager::CreateCircuitbyLabel (label_t bnode_label) [private]
create a circuit from the given node's label.
Parameters
bnode_label is label_t
Returns
none
References FindOrAddToCircuitbyLabel(), and set_of_circuit_OUT.
Referenced by CreateCircuitFromOutputList().
void bench_circuit_manager::CreateCircuitFromOutputList (void) [private]
create a circuit from the labels in the set_of_output_labels.
Parameters
none
Returns
none
References CreateCircuitbyLabel(), labels2uuid_table, set_of_flipflop_labels, set_of_output_labels, and uuid2circuitNode_table.
Referenced by bench_circuit_manager().
unique_ID_t bench_circuit_manager::FindOrAddToCircuit (bench_node_t bench_node) [private]
search or add the node to the circuit.
Parameters
bench_node is bench_node_t
Returns
unique_ID_t representing the given bench_node
It searches if the bench node exist in the label2uuid_table. If it does't, adds it to the table and return the unique ID. Otherwise, simply return the unique ID of the node.
References BenchNode2CircuitNode(), circuit_node_type::ID, labels2uuid_table, and uuid2circuitNode_table.
Referenced by FindOrAddToCircuitbyLabel().
unique_ID_t bench_circuit_manager::FindOrAddToCircuitbyLabel (label_t node_label) [private]
find or add a node to the circuit given its label.
Parameters
node_label is label_t
Returns
unique_ID_t representing the given label
It searches if the node corresponding to the given label is already inserted into the labels2uuid_table table. If it is, returns its id. If not, creates a new node into the circuit and add it to the table.
References FindOrAddToCircuit(), and labels2node_table.
Referenced by BenchNode2CircuitNode(), and CreateCircuitbyLabel().
boost::unordered_map< unique_ID_t, circuit_node_type > bench_circuit_manager::GetCircuit (void) [private]
return the table representing the circuit.
Parameters
none
Returns
boost::unordered_map<unique_ID_t, circuit_node_type>
References uuid2circuitNode_table.
circuit_node_type bench_circuit_manager::GetCircuitNode (unique_ID_t circuit_node_uuid) [private]
return a circuit node, given a its unique ID.
Parameters
circuit_node_uuid is unique_ID_t
Returns
circuit_node_type
References uuid2circuitNode_table.
Referenced by TopologicalSortKahnsAlgorithm().
set_of_circuit_t bench_circuit_manager::GetListOfCircuitsInputs (void) [private]
return a list with the UUID of the INPUT gates of the circuit.
Parameters
none
Returns
set_of_circuit_t
References set_of_circuit_IN.
set_of_circuit_t bench_circuit_manager::GetListOfCircuitsOutputs (void) [private]
return a list with the UUID of the OUTPUT gates of the circuit.
Parameters
none
Returns
set_of_circuit_t
References set_of_circuit_OUT.
Referenced by TopologicalSortKahnsAlgorithm().
std::set< label_t > bench_circuit_manager::GetListOfOutputLabels (void)
return a list with the labels of the OUTPUT gates of the circuit.
The label's list also includes the FLIP_FLOPS
Parameters
none
Returns
std::set<label_t>
list_of_circuit_t bench_circuit_manager::GetSortedCircuit (void)
return the list of circuit nodes topologically sorted.
Parameters
none
Returns
list_of_circuit_t
References sorted_circuit.
Referenced by PrintSortedCircuitList().
bool bench_circuit_manager::IsUniqueOutgoingEdge (unique_ID_t src_node, unique_ID_t dst_node) [private]
auxiliar function for topological sort algorithms.
Parameters
src_node is unique_ID_t
dst_node is unique_ID_t
Returns
True if it was the only outgoing edge. False, otherwise.
It removes the edge from src->dst at the table uuid2circuitNode and then checks if it was the only outgoing edge.
References uuid2circuitNode_table.
Referenced by TopologicalSortKahnsAlgorithm().
bool bench_circuit_manager::ParseFile (std::string bench_file) [private]
Reads the file containing the circuit in the bench format.
Parameters
bench_file is std::string.
Returns
bool returns true in case of success.
Reads the file containing the circuit in the bench format.
References AddToLabelsTable().
Referenced by bench_circuit_manager().
void bench_circuit_manager::PrintCircuit (unique_ID_t circuit_ID, int indent) [private]
prints the circuit starting from the given unique identificator.
Parameters
circuit_ID is unique_ID_t corresponding to a node circuit.
indent is int and represents the depth of the node in the circuit.
Returns
none
It prints the circuit starting from circuit_ID node. Indent is an integer corresponding to the depth of the node in the circuit. Each unity will add four spaces as identation before printing the node's data.
References circuit_node_type::gate_type, circuit_node_type::ID, circuit_node_type::input_ID_list, circuit_node_type::label, circuit_node_type::output_ID_list, and uuid2circuitNode_table.
Referenced by PrintCircuitByLabel(), and PrintCircuitsOfOutputSet().
void bench_circuit_manager::PrintCircuitByLabel (label_t node_label) [private]
prints the circuit starting from the given label's node.
Parameters
node_label is label_t
Returns
none
References labels2uuid_table, and PrintCircuit().
void bench_circuit_manager::PrintCircuitsOfOutputSet (void) [private]
prints all circuits from the set of circuit OUTPUTS.
Parameters
none
Returns
none
References PrintCircuit(), and set_of_circuit_OUT.
void bench_circuit_manager::PrintLabels2UUIDTable (void) [private]
Print the labels2uuid_table table.
Parameters
none
Returns
none
It prints all the labels and its associates unique circuit ID.
References labels2uuid_table.
void bench_circuit_manager::PrintLabelsTable (void) [private]
Print the labels2node_table table.
Parameters
none
Returns
none
It prints all the labels and the data associated to bench nodes.
References labels2node_table.
void bench_circuit_manager::PrintOutputList (void) [private]
Print the set_of_output_labels list.
Parameters
none
Returns
none
It prints the list containing the label of all output nodes.
References set_of_output_labels.
void bench_circuit_manager::PrintSortedCircuitList (void) [private]
prints the list of topological sorted circuit's node.
Parameters
none
Returns
none
References GetSortedCircuit().
void bench_circuit_manager::PrintUUIDCircuitTable (void) [private]
Print the uuid2circuitNode_table table.
Parameters
none
Returns
none
It prints all the unique IDs and the data associated to circuit nodes.
References uuid2circuitNode_table.
void bench_circuit_manager::TopologicalSortKahnsAlgorithm (void) [private]
Implementation of Kahn's Algorithm for topological sort.
Parameters
none
Returns
none (the result is stored at sorted_circuit variable)
References GetCircuitNode(), GetListOfCircuitsOutputs(), circuit_node_type::ID, circuit_node_type::input_ID_list, IsUniqueOutgoingEdge(), sorted_circuit, and uuid2circuitNode_table.
Referenced by bench_circuit_manager().
Member Data Documentation
std::set<label_t> bench_circuit_manager::set_of_flipflop_labels [private]
Set containing bench node labels of all FLIP FLOP gates.
When a FLIP FLOP bench gate is parsed, it is splitted into two circuit's gates: one will be handled as INPUT gate and the other one as OUTPUT gate.
Referenced by AddToLabelsTable(), bench_circuit_manager(), and CreateCircuitFromOutputList().
The documentation for this class was generated from the following files:
/home/felipe/Desktop/vdsproject/vdscp_04/src/bench/bench_circuit_manager.hpp
/home/felipe/Desktop/vdsproject/vdscp_04/src/bench/bench_circuit_manager.cpp